### ISSUE TITLE
idea调试问题

### ISSUE THREAD

**Issue by zqq525** [kangjianwei/OpenJDK-11#1]
咨询一下，如何用idea实现不关联jdk?

运行BreakIteratorTest01，部分报错信息
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl$$Lambda$129/0x00000008003bc040.call(Unknown Source)
Information:java: Errors occurred while compiling module 'OpenJDK-11'
Information:javac 11 was used to compile java sources
Error:java: OutOfMemoryError: insufficient memory

**Comment by zqq525** [comment]
已解决，谢谢~~~
